protected/controllers/SiteController.php
<?php

class SiteController extends Controller {

    /**
     * Declares class-based actions.
     */
    public function actions() {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex() {
        $model = new LoginForm;
        if (Yii::app()->user->isGuest) {
            // if it is ajax validation request
            if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
                echo CActiveForm::validate($model);
                Yii::app()->end();
            }

            // collect user input data
            if (isset($_POST['LoginForm'])) {
                $model->attributes = $_POST['LoginForm'];
                // validate user input and redirect to the previous page if valid
                if ($model->validate() && $model->login())
                    $this->redirect(Yii::app()->user->returnUrl);
            }

            // renders the view file 'protected/views/site/index.php'
            // using the default layout 'protected/views/layouts/main.php'
            $this->render('index', array('model' => $model));
        } else {
            $this->render('profile', array('model' => $model));
        }
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError() {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    /**
     * Displays the contact page
     */
    public function actionContact() {
        $model = new ContactForm;
        if (isset($_POST['ContactForm'])) {
            $model->attributes = $_POST['ContactForm'];
            if ($model->validate()) {
                $name = '=?UTF-8?B?' . base64_encode($model->name) . '?=';
                $subject = '=?UTF-8?B?' . base64_encode($model->subject) . '?=';
                $headers = "From: $name <{$model->email}>\r\n" .
                    "Reply-To: {$model->email}\r\n" .
                    "MIME-Version: 1.0\r\n" .
                    "Content-type: text/plain; charset=UTF-8";

                mail(Yii::app()->params['adminEmail'], $subject, $model->body, $headers);
                Yii::app()->user->setFlash('contact', 'Thank you for contacting us. We will respond to you as soon as possible.');
                $this->refresh();
            }
        }
        $this->render('contact', array('model' => $model));
    }

    /**
     * Displays the login page
     */
    public function actionLogin() {
        $model = new LoginForm;

        // if it is ajax validation request
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid
            if ($model->validate() && $model->login())
                $this->redirect(Yii::app()->user->returnUrl);
        }
        // display the login form
        $this->render('login', array('model' => $model));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout() {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }

    public function beforeAction($action) {
        if (parent::beforeAction($action)) {
            /* @var $cs CClientScript */
            $cs = Yii::app()->clientScript;
            /* @var $theme CTheme */
            $theme = Yii::app()->theme;
            $cs->registerPackage('jquery');
            $cs->registerPackage('history');
            $cs->registerPackage('jquery-cookie');
            $cs->registerPackage('jquery-easing');
            $cs->registerPackage('soundcloud');
            $cs->registerScriptFile(Yii::app()->request->baseUrl . '/javascripts/main.js');
//                $cs->registerCssFile($theme->getBaseUrl() . '/css/main.css');
            return true;
        }
        return false;
    }

}

protected/controllers/UsersController.php
<?php

class UsersController extends Controller {
        public function actions() {
        // captcha action renders the CAPTCHA image displayed on the register page
        return array(
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
                'foreColor' => 0xfb8112,
                'offset' => 5,
            ),
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    public function actionIndex() {
        $model = new Users;

        if (isset($_POST['ajax']) && $_POST['ajax'] === 'users-index-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        if (isset($_POST['Users'])) {
            $model->attributes = $_POST['Users'];
            if ($model->validate()) {
                if ($model->save()) {
                    $this->redirect(array('site/login'));
                }
                return;
            }
        }
        $this->render('index', array('model' => $model));
    }
    public function beforeAction($action) {
        if( parent::beforeAction($action) ) {
            /* @var $cs CClientScript */
            $cs = Yii::app()->clientScript;
            /* @var $theme CTheme */
            $theme = Yii::app()->theme;
            $cs->registerPackage('jquery');
            $cs->registerPackage('history');
            $cs->registerPackage('jquery-cookie');
            $cs->registerPackage('jquery-easing');
            $cs->registerPackage('soundcloud');
            $cs->registerScriptFile( Yii::app()->request->baseUrl.'/javascripts/main.js');
//                $cs->registerCssFile($theme->getBaseUrl() . '/css/main.css');
            return true;
        }
        return false;
    }
}

protected/views/site/contact.php
<?php
/* @var $this SiteController */
/* @var $model ContactForm */
/* @var $form CActiveForm */

    $this->layout = 'modal';
    $this->pageTitle=Yii::app()->name . ' - Contact Us';
    $this->breadcrumbs=array(
            'Contact',
    );
    $this->pageclass = 'modal-page feedback-page';
    $this->maintitle = 'get in touch';
    $this->subtitle = 'because your opinion matters!';
    $this->headimage = '/storage/images/backgrounds/4a.jpg';
?>
<?php if(Yii::app()->user->hasFlash('contact')): ?>
    <div class="flash-success">
        <?php echo Yii::app()->user->getFlash('contact'); ?>
    </div>
    <?php else: ?>
    <p>
        If you have business inquiries or other questions, 
        please fill out the following form to contact us.
    </p>
    <div class="form-block">
        <?php
            $form = $this->beginWidget('CActiveForm', array(
                'id' => 'contact-form',
                'enableClientValidation' => true,
                'clientOptions' => array(
                    'validateOnSubmit' => true,
                ),
                'htmlOptions'=>array(
                    'class'=>'form',
                ),
            ));
        ?>
        <p class="note">Fields below are required *</p>
        <?php echo $form->errorSummary($model); ?>
        <div class="row no-margin">
            <div class="input-field">
                <?php echo $form->labelEx($model,'name'); ?>
                <?php echo $form->textField($model,'name', array( 'placeholder'=>'e.g. John Smith', 'class'=>'input username')); ?>
                <?php echo $form->error($model, 'name'); ?>
            </div>
            <div class="input-field">
                <?php echo $form->labelEx($model,'email'); ?>
                <?php echo $form->textField($model,'email', array( 'placeholder'=>'e.g. john.smith@aboree.com', 'class'=>'input email')); ?>
                <?php echo $form->error($model, 'email'); ?>
            </div>
        </div>
        <div class="row no-margin">
            <div class="input-field">
                <?php echo $form->labelEx($model,'subject'); ?>
                <?php echo $form->textField($model, 'subject', array('size' => 60, 'maxlength' => 128, 'placeholder'=>'You guys, are awesome.', 'class'=>'input subject')); ?>
                <?php echo $form->error($model, 'subject'); ?>
            </div>
        </div>
        <div class="row no-margin">
            <div class="input-field">
                <?php echo $form->labelEx($model,'body'); ?>
                <?php echo $form->textArea($model, 'body', array('rows' => 6, 'cols' => 50, 'class'=>'textarea', 'placeholder'=>'aboree is my new favourite web application.')); ?>
                <?php echo $form->error($model, 'body'); ?>
            </div>
        </div>
        <?php if (CCaptcha::checkRequirements()): ?>
        <div class="row no-margin">
            <div class="captcha-form">
                <div class="row no-margin">
                    <?php echo $form->labelEx($model, 'verifyCode'); ?>
                   <?php $this->widget('CCaptcha'); ?>
                    <div class="input-field">
                        <?php echo $form->textField($model, 'verifyCode', array('class'=>'input captcha-field')); ?>
                    </div> 
                </div>
                <div class="note">Please enter the letters as they are shown in the image above.
                    <br/>Letters are not case-sensitive.
                </div>
                <?php echo $form->error($model, 'verifyCode'); ?>
            </div>
        </div>
        <?php endif; ?>
        <div class="row no-margin buttons">
            <?php echo CHtml::resetButton('start over', array('class'=>'reset-button')); ?>
            <?php echo CHtml::submitButton('Submit', array('class'=>'button')); ?>
        </div>
        <?php $this->endWidget(); ?>
    <!-- form -->
    </div>
<?php endif; ?>

protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

protected/views/site/index.php
<?php
/* @var $this SiteController */

$this->pageTitle = Yii::app()->name;

$this->pageclass = 'home-page';
?>
<?php if (Yii::app()->user->isGuest) { ?>
    <div class="front-containter">
        <div class="image-wrapper">
            <video id="guest_video" class="main-image" autoplay loop preload="auto">
                <source src="storage/videos/background.mp4" type='video/mp4' />
                <source src="storage/videos/background.webm" type='video/webm' />
                <source src="storage/videos/background.ogv" type='video/ogg' />
            </video>
        </div>
        <div class="dots">
            <?php include dirname(dirname(__FILE__)).'/static/header.php'; ?>
            <div class="container">
                <div class="home-wrapper">
                    <div class="welcome">
                        <h1 class="welcome-notice">welcome to <?php echo CHtml::encode(Yii::app()->name); ?></h1>
                        <span class="welcome-slogan">...what happened last night?</span>
                    </div>
                    <div class="user-wrapper">
                        <div class="form-block">
                            <!--Login form start-->
                            <?php $form=$this->beginWidget('CActiveForm', array(
                                    'id'=>'login-form',
                                    'enableClientValidation'=>true,
                                    'clientOptions'=>array(
                                            'validateOnSubmit'=>true,
                                    ),
                                    'htmlOptions'=>array(
                                        'class'=>'form',
                                        'autocomplete'=>'off',
                                    ),
                            )); ?>
                            <div class="row no-margin">
                                <div class="input-field">
                                    <div class="username-field">
                                        <?php echo $form->textField($model,'username', array( 'placeholder'=>'username', 'class'=>'input username', 'autocomplete'=>'off', )); ?>
                                        <?php echo $form->error($model,'username'); ?>
                                    </div>
                                    <div class="password-field">
                                        <?php echo $form->passwordField($model,'password', array('placeholder'=>'password', 'class'=>'input password')); ?>
                                        <?php echo $form->error($model,'password'); ?>
                                    </div>
                                </div>
                                <?php echo CHtml::submitButton('login', array('class'=>'login-button')); ?>
                                <div class="clearfix"></div>
                            </div>
                            <!--<div class="row rememberMe">-->
                                <?php // echo $form->checkBox($model,'rememberMe'); ?>
                                <?php // echo $form->label($model,'rememberMe'); ?>
                                <?php // echo $form->error($model,'rememberMe'); ?>
                            <!--</div>-->
                        <?php $this->endWidget(); ?>
                        <!--Login form end-->
                        </div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
<?php } ?>

protected/views/site/login.php
<?php
/* @var $this SiteController */
/* @var $model LoginForm */
/* @var $form CActiveForm  */

    $this->layout = 'modal';
    $this->pageTitle = Yii::app()->name . ' - Login';
    $this->breadcrumbs = array(
        'Login',
    );
    
    $this->pageclass = 'modal-page login-page';
    $this->maintitle = 'login to aboree';
    $this->subtitle = 'enjoy your party night';
    $this->headimage = '/storage/images/backgrounds/5a.jpg';
?>
<p>Please fill out the following form with your login credentials:</p>
<div class="row no-margin">
    <div class="form-block">
        <?php
            $form = $this->beginWidget('CActiveForm', array(
                'id' => 'login-form',
                'enableClientValidation' => true,
                'clientOptions' => array(
                    'validateOnSubmit' => true,
                ),
                'htmlOptions'=>array(
                    'class'=>'form',
                ),
            ));
        ?>
        <p class="note">Fields below are required *</p>
        <div class="input-field">
            <?php echo $form->textField($model,'username', array( 'placeholder'=>'username', 'class'=>'input username')); ?>
            <?php echo $form->error($model,'username'); ?>
            <a class="fg urnm" href="#">forgot your username?</a>
        </div>
        <div class="input-field">
            <?php echo $form->passwordField($model,'password', array('placeholder'=>'password', 'class'=>'input password')); ?>
            <?php echo $form->error($model,'password'); ?>
            <a class="fg psd" href="#">forgot your password?</a>
        </div>
        <div class="clearfix"></div>
        <p class="hint">
            <b><i>Hint:</i></b> You can try aboree with demo account. login with <kbd>demo</kbd>/<kbd>demo</kbd>
        </p>
        <div class="rememberMe">
            <?php echo $form->checkBox($model, 'rememberMe'); ?>
            <?php echo $form->label($model, 'rememberMe'); ?>
            <?php echo $form->error($model, 'rememberMe'); ?>
        </div>
        <?php echo CHtml::submitButton('Login', array('class'=>'login-button')); ?>
        <?php $this->endWidget(); ?>
    </div>
</div>
<div class="row no-margin">
    <div class="login-separator">
        <span>or</span>
    </div>
</div>
<div class="row no-margin">
    <div class="social-media-login">
        <div class="facebook">
            <span class="icon"></span>
            <span class="social-media-login-text">facebook connect</span>
        </div>
        <div class="twitter">
            <span class="icon"></span>
            <span class="social-media-login-text">sign in with twitter</span>
        </div>
    </div>
</div>

<div class="agreement">
    If you use "facebook connect" or "sign in with twitter" and are not an aboree user,<br /> 
    you will be registered and you agree to aboree's 
    <a href="<?php echo $this->createUrl('site/page',array('view'=>'privacy'))?>"><u>privacy policy</u></a>.
</div>
<div class="form-block-footer">
    Not a member yet? <a href="<?php echo $this->createUrl('users/index')?>">Register now</a> - it's free and easy!
</div>           

protected/views/site/profile.php
<?php
/* @var $this SiteController */

    $this->layout='profile';
    $this->pageTitle='hello '. Yii::app()->user->name;
    $this->breadcrumbs=array(
            'about',
    );
    $this->pageclass= 'profile-page';
?>
<div class="profile-content-wrapper">
    <div class="profile-content">
        <div class="clearfix"></div>
        <div class="main-cotrols">
            <div class="control-button check-mates">check your mates</div>
            <div class="control-button last-night">#?%! last night</div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>